[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[tool.black]
line-length = 79
target-version = ["py310"]

testpaths = [
    "tests"
]

[tool.pytest.ini_options]
markers = [
    "UNIFAC: classic UNIFAC model tests",
    "CH2: CH3, CH2, CH, C",
    "CeqC: CH2=CH, CH=CH, CH2=C, CH=C, C=C",
    "ACH: ACH, AC",
    "ACCH2: ACCH3, ACCH2, ACCH",
    "OH: OH, CH3OH",
    "H2O: H2O",
    "ACOH: ACOH",
    "CH2CO: CH3CO, CH2CO",
    "CHO: CHO",
    "CCOO: CH3COO, CH2COO",
    "HCOO: HCOO",
    "CH2O: CH2O, CH-O, THF",
    "mix: a mix of a lot of subgroupss"
]

[project]
name = "ugropy"
version = "0.0.1"
authors = [{name = "Brandolín, Salvador Eduardo", email = "salvadorebrandolin@mi.unc.edu.ar"}]
license = {text = "All rights reserved"}
readme = "README.md"
description = "Get UNIFAC functional groups of PubChem compounds"
keywords = ["UNIFAC", "functional group", "thermodynamics", "chemical engineering"]
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering",
]

urls = {Homepage = "https://github.com/SalvadorBrandolin/ugrupy"}

dependencies = [
    'numpy >= 1.25.1',
    'pandas >= 2.0.3',
    'pubchempy == 1.0.4',
    'rdkit == 2023.3.2'
]
